CREATE TABLE IF NOT EXISTS users (
  user_id UUID PRIMARY KEY NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP
);