global:
  scrape_interval: 5s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "banking-app"
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:8080'] # Use 'localhost:8080' if Prometheus and the metrics source are on the same machine without Docker.
  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323", "host.docker.internal:9100"]