{
 "title": "OpenIdea Bank App",
 "description": "Dashboard for applications that use https://github.com/ansrivas/fiberprometheus",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "DataSource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(http_requests_total, namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_requests_total, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_requests_total, instance)"
    }
   },
   {
    "name": "handler",
    "label": "Handler",
    "query": {
     "query": "label_values(http_requests_total, path)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Utilities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "datasource" },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{id=\"/\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{name=~\".+\"}[1m])) + sum(rate(container_cpu_system_seconds_total{id=\"/\"}[1m])) + sum(rate(process_cpu_seconds_total[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{name=~\".+\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{device=\"/dev/vda1\", mountpoint=\"/etc/hostname\"} / node_filesystem_size_bytes{device=\"/dev/vda1\", mountpoint=\"/etc/hostname\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemAvailable_bytes - node_memory_MemFree_bytes)/1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"eth0\"}[$__rate_interval]) / 1000000",
     "legendFormat": "network receive (mbps)"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"eth0\"}[$__rate_interval]) / 1000000",
     "legendFormat": "network sent (mbps)"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{job=\"banking-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"host.docker.internal:8080\",job=\"banking-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic - Req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[2m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic by instance - Req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[2m])) by (job, instance)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ instance }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic - Req/s by handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[2m])) by (job, method, path)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors - % (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\", status=\"500|502|503|504\"}[5m])) by (job)/sum(rate(http_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])) by (job)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "__auto",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Errors - % by handler (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(rate(http_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\", status=\"500|502|503|504\"}[5m])) by (job, method, handler)/sum(rate(http_requests_total{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])) by (job, method, handler)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{handler}}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latêncy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency - General",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - p99"
    }
   ]
  },
  {
   "title": "Latency by handler",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, method, handler, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ method }} {{ handler }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, method, handler, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ handler }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, method, handler, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ method }} {{ handler }} - p99"
    }
   ]
  },
  {
   "title": "Latency by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "histogram_quantile(0.5, sum by (job, instance, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ job }} - {{ instance }} - p50",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "expr": "histogram_quantile(0.95, sum by (job, instance, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p99"
    }
   ]
  },
  {
   "title": "Latency 99p by instance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (job, instance, le) (rate(http_request_duration_seconds_bucket{job=~\"$job\",instance=~\"$instance\", path=~\"$handler\", namespace=~\"$namespace\"}[5m])))",
     "legendFormat": "{{ job }} - {{ instance }} - p99"
    }
   ]
  }
 ]
}