name: HyperBank Docker Push
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  hyperbank-build:
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout
          uses: actions/checkout@v2    
          
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{secrets.AWS_REGION}}
        - name: Get secret file
          env:
            DB_SECRET_PEM: ${{ secrets.DB_PEM }}
          run: echo "${DB_SECRET_PEM}" > database_secret.pem

        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{  steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
            IMAGE_TAG: latest
          run: |
            docker build -t 560918124458.dkr.ecr.ap-southeast-1.amazonaws.com/hyperbank-backend:latest --file ./dockerfiles/backend/Dockerfile .
            docker push 560918124458.dkr.ecr.ap-southeast-1.amazonaws.com/hyperbank-backend:latest
