name: HyperBank Docker Push
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  hyperbank-build:
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout
          uses: actions/checkout@v2    
          
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: ${{secrets.AWS_REGION}}
        - name: Get secret file
          env:
            DB_PEM: ${{ secrets.DB_PEM }}
            APP_TASK_DF: ${{ secrets.AWS_APP_DEPLOY_TASK_DEFINITION }}
          run: |
            echo "$DB_PEM" > database_secret.pem
            echo "$APP_TASK_DF" > task_definition.json

        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v2

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
            IMAGE_TAG: latest
          run: |
            docker build -t ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}} --file ./dockerfiles/backend/Dockerfile .
            docker push ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}
        
        - name: Fill in the new image ID in the Amazon ECS task definition
          id: task-def
          uses: aws-actions/amazon-ecs-render-task-definition@v1
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
            IMAGE_TAG: latest
          with:
              task-definition: task_definition.json
              container-name: hyperbank-bankend
              image: ${{env.ECR_REGISTRY}}/${{env.ECR_REPOSITORY}}:${{env.IMAGE_TAG}}

        - name: Deploy to Amazon ECS service
          uses: aws-actions/amazon-ecs-deploy-task-definition@v1
          with:
            task-definition: ${{ steps.render-web-container.outputs.task-definition }}
            service: hyperbank-deploy-service
            cluster: hyperbank-dev
